name: Build and Test

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:
  repository_dispatch:
    types: [ build ]

jobs:
  build:
    name: Build and Test
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Run integration tests
        run: ./gradlew test i
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.4.1
        if: always()
        with:
          files: |
            test-results/**/*.xml